#!/usr/bin/env python
import rospy
import actionlib
import numpy as np
import sounddevice as sd

from dynamic_reconfigure.server import Server as DynServer

from pal_interaction_msgs.msg import TtsAction, TtsGoal, TtsResult, TtsFeedback

from piper_tts import piper_tts


class PiperTTSPal(object):
    # create messages that are used to publish feedback/result
    _feedback = TtsFeedback()
    _result = TtsResult()

    def __init__(self, model_dir, default_model):
        self.model_dir = model_dir

        self.voices = {}
        model, config = piper_tts.get_model(model_dir, default_model)
        self.voices["default"] = piper_tts.PiperTTS(model, config)

        self.configure()

        # This is just to warmup the default network
        data = self.voices["default"].synthesize("Good Morning")
        for d in data:
            pass

        self._as = actionlib.SimpleActionServer(
            "/piper_tts",
            TtsAction,
            execute_cb=self.execute_cb,
            auto_start=False,
        )
        self._as.start()

        self._tts_client = actionlib.SimpleActionClient("/tts", TtsAction)
        rospy.loginfo("waiting for /tts connection...")
        self._tts_client.wait_for_server()
        rospy.loginfo("Connected to /tts")

        rospy.loginfo("piper_tts started")

    def configure(self):
        meta_param = rospy.get_param("/piper_tts/models")
        print(meta_param)

        param_names = rospy.get_param_names()
        self.model_names = []
        for param_name in param_names:
            # If the parameter is like '/piper_tts/models/NAME/voice'
            if "/piper_tts/models" in param_name and "/voice" in param_name:
                motion_name = param_name.replace("/piper_tts/models/", "")
                motion_name = motion_name.replace("/voice", "")
                self.model_names.append(motion_name)

        for model in self.model_names:
            param = rospy.get_param(f"/piper_tts/models/{model}")
            voice = param["voice"]

            rospy.loginfo(f"Loading /piper_tts/models/{model} with {voice}")
            try:
                onnx, config = piper_tts.get_model(self.model_dir, voice)
                self.voices[model] = piper_tts.PiperTTS(onnx, config)
            except rospy.ROSException as e:
                rospy.logwarn(f"could not load '{model}', ignored")

    def get_voice(self, langid):
        if langid in self.voices.keys():
            return self.voices[langid]
        else:
            rospy.logerr(f"failed to find language {langid}")
            return None

    def forward(self, goal):
        goal.rawtext.lang_id = "en_GB"
        self._tts_client.send_goal(goal)
        while self._tts_client.wait_for_result(rospy.Duration(0.01)) != True:
            if self._as.is_preempt_requested():
                self._tts_client.cancel_goal()
                return self._as.set_preempted()

        self._as.set_succeeded()

    def execute_cb(self, goal: TtsGoal):
        r = rospy.Rate(10)
        success = True

        if goal.rawtext.lang_id == "" or goal.rawtext.lang_id == "en_GB":
            return self.forward(goal)

        rospy.loginfo(f"say({goal.rawtext.lang_id}): {goal.rawtext.text}")

        voice = self.get_voice(goal.rawtext.lang_id)
        if voice is None:
            self._as.set_aborted()
            return

        audio_stream = voice.synthesize(goal.rawtext.text)

        for data in audio_stream:
            npa = np.frombuffer(data, dtype=np.int16)
            # RawOutputStream does not need np
            sd.play(npa, voice.samplerate, blocking=False)

            while sd._last_callback.event.is_set() == False:
                if self._as.is_preempt_requested():
                    sd.stop()
                    self._as.set_preempted()
                    return
                rospy.sleep(0.1)

            if self._as.is_preempt_requested():
                sd.stop()
                self._as.set_preempted()
                success = False
                return

        rospy.loginfo(f"playback done {success}")

        if success:
            self._as.set_succeeded()
        else:
            self._as.set_aborted()


if __name__ == "__main__":

    # Start ROS node
    rospy.init_node("piper_tts_pal")
    model_dir = rospy.get_param("~model_dir", "/home/robocup-adm/tmp/tts/karlsson")
    default_model = rospy.get_param("~default_model", "de_DE-karlsson-low")
    PiperTTSPal(model_dir, default_model)
    rospy.spin()
